/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
plugins {
    kotlin("plugin.allopen")
}
/*
allOpen {
    annotation("com.cis.iac.UseCase")
}
*/

dependencies {

    implementation("com.capraro:kalidation:1.4.1")

}